name: Compute permission diff on PR

on:
  pull_request:

jobs:
  compute-diff:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: InvariantClub/metadelta-github-action@v1
        with:
          # Repo-relative path to the hasura metadata folder.
          hasura_path: hasura/metadata
